# Generated by Django 3.2.7 on 2021-09-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('session_id', models.UUIDField()),
                ('timestamp', models.DateTimeField()),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('schema', models.JSONField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='schema',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='OneSchemaPerCategoryName'),
        ),
    ]
